name: cold_chain_driver
description: 冷链司机记账App - 充电费、过路费、停车费、货物买赔管理
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  fl_chart: any
  google_fonts: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
